<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PokeChat.Application\PokeChat.Application.csproj" />
    <ProjectReference Include="..\PokeChat.Domain\PokeChat.Domain.csproj" />
  </ItemGroup>

</Project>
