name: Dependency Review

on:
  pull_request:
    branches: [main, master]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Dependency Review
        uses: actions/dependency-review-action@ce3cf9537a52e8119d91fd484ab5e8a0c7a1c1a5 # v4
        with:
          fail-on-severity: moderate
          deny-licenses: GPL-2.0, GPL-3.0
